name: Build and Release on Tag

on:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build solution
        run: dotnet build PartyFinderToolbox.sln --configuration Release

      - name: Publish
        run: dotnet publish YourSolution.sln --configuration Release --output ./publish

      - name: Create zip
        run: Compress-Archive -Path ./publish/* -DestinationPath ./release.zip

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body: "Automated release for ${{ github.ref_name }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release.zip
          asset_name: release.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
